// ============================================================================
// Auto-generated C Header for LCD_CTRL
// Version: 1.0
// ============================================================================
// IMPORTANT: This file is auto-generated. Manual edits may be lost.
// For changes: Modify the XLS specification and regenerate.
// ============================================================================

#ifndef __LCD_REGS_H__
#define __LCD_REGS_H__

#define LCD_BASE_ADDRESS 0x0

// ----------------------------------------------------------------------------
// Register Offsets
// ----------------------------------------------------------------------------
#define LCD_LCD_CTRL_OFFSET (LCD_BASE_ADDRESS + 0x000)
#define LCD_LCD_STATUS_OFFSET (LCD_BASE_ADDRESS + 0x004)
#define LCD_LCD_IRQ_EN_OFFSET (LCD_BASE_ADDRESS + 0x008)
#define LCD_LCD_FB0_ADDR_OFFSET (LCD_BASE_ADDRESS + 0x00c)
#define LCD_LCD_FB1_ADDR_OFFSET (LCD_BASE_ADDRESS + 0x010)
#define LCD_LCD_STRIDE_OFFSET (LCD_BASE_ADDRESS + 0x014)
#define LCD_LCD_PU_X_OFFSET (LCD_BASE_ADDRESS + 0x018)
#define LCD_LCD_PU_Y_OFFSET (LCD_BASE_ADDRESS + 0x01c)
#define LCD_LCD_SPI_CFG_OFFSET (LCD_BASE_ADDRESS + 0x020)
#define LCD_LCD_TE_CFG_OFFSET (LCD_BASE_ADDRESS + 0x024)
#define LCD_LCD_RESX_CFG0_OFFSET (LCD_BASE_ADDRESS + 0x028)
#define LCD_LCD_RESX_CFG1_OFFSET (LCD_BASE_ADDRESS + 0x02c)
#define LCD_LCD_CMD_FIFO_OFFSET (LCD_BASE_ADDRESS + 0x030)
#define LCD_LCD_CMD_STATUS_OFFSET (LCD_BASE_ADDRESS + 0x034)
#define LCD_LCD_ERR_ADDR_OFFSET (LCD_BASE_ADDRESS + 0x038)
#define LCD_LCD_VERSION_OFFSET (LCD_BASE_ADDRESS + 0x03c)
#define LCD_LCD_INFO_OFFSET (LCD_BASE_ADDRESS + 0x040)
#define LCD_LCD_FRAME_CTRL_OFFSET (LCD_BASE_ADDRESS + 0x044)
#define LCD_LCD_LINEBUF_STATUS_OFFSET (LCD_BASE_ADDRESS + 0x048)
#define LCD_LCD_SLAVE_BUFA_ADDR_OFFSET (LCD_BASE_ADDRESS + 0x04c)
#define LCD_LCD_SLAVE_BUFB_ADDR_OFFSET (LCD_BASE_ADDRESS + 0x050)
#define LCD_LCD_SLAVE_INFO_OFFSET (LCD_BASE_ADDRESS + 0x054)

// ----------------------------------------------------------------------------
// Register Reset Values
// Usage: uint32_t expected = SIM_SIM_XXX_RESET;
// ----------------------------------------------------------------------------
#define LCD_LCD_CTRL_RESET 0x00000800U
#define LCD_LCD_STATUS_RESET 0x00000000U
#define LCD_LCD_IRQ_EN_RESET 0x00000000U
#define LCD_LCD_FB0_ADDR_RESET 0x00000000U
#define LCD_LCD_FB1_ADDR_RESET 0x00000000U
#define LCD_LCD_STRIDE_RESET 0x00000000U
#define LCD_LCD_PU_X_RESET 0x00000000U
#define LCD_LCD_PU_Y_RESET 0x00000000U
#define LCD_LCD_SPI_CFG_RESET 0x0000F100U
#define LCD_LCD_TE_CFG_RESET 0x00FF0101U
#define LCD_LCD_RESX_CFG0_RESET 0x00000064U
#define LCD_LCD_RESX_CFG1_RESET 0x00000064U
#define LCD_LCD_CMD_FIFO_RESET 0x00000000U
#define LCD_LCD_CMD_STATUS_RESET 0x00000180U
#define LCD_LCD_ERR_ADDR_RESET 0x00000000U
#define LCD_LCD_VERSION_RESET 0xAC1D0100U
#define LCD_LCD_INFO_RESET 0x001400F0U
#define LCD_LCD_FRAME_CTRL_RESET 0x00000000U
#define LCD_LCD_LINEBUF_STATUS_RESET 0x0000000CU
#define LCD_LCD_SLAVE_BUFA_ADDR_RESET 0x00000000U
#define LCD_LCD_SLAVE_BUFB_ADDR_RESET 0x00000000U
#define LCD_LCD_SLAVE_INFO_RESET 0x00000400U

// ----------------------------------------------------------------------------
// Field Definitions (SHIFT, WIDTH, MASK)
// Usage: val = (reg >> SHIFT) & ((1 << WIDTH) - 1)
//        reg = (reg & ~MASK) | ((val << SHIFT) & MASK)
// ----------------------------------------------------------------------------
#define LCD_LCD_CTRL_LCD_EN_SHIFT  0U
#define LCD_LCD_CTRL_LCD_EN_WIDTH  1U
#define LCD_LCD_CTRL_LCD_EN_MASK   0x00000001U

#define LCD_LCD_CTRL_DMA_EN_SHIFT  1U
#define LCD_LCD_CTRL_DMA_EN_WIDTH  1U
#define LCD_LCD_CTRL_DMA_EN_MASK   0x00000002U

#define LCD_LCD_CTRL_TE_EN_SHIFT  2U
#define LCD_LCD_CTRL_TE_EN_WIDTH  1U
#define LCD_LCD_CTRL_TE_EN_MASK   0x00000004U

#define LCD_LCD_CTRL_CMD_SEQ_EN_SHIFT  3U
#define LCD_LCD_CTRL_CMD_SEQ_EN_WIDTH  1U
#define LCD_LCD_CTRL_CMD_SEQ_EN_MASK   0x00000008U

#define LCD_LCD_CTRL_STREAM_MODE_SHIFT  4U
#define LCD_LCD_CTRL_STREAM_MODE_WIDTH  1U
#define LCD_LCD_CTRL_STREAM_MODE_MASK   0x00000010U

#define LCD_LCD_CTRL_PARTIAL_EN_SHIFT  5U
#define LCD_LCD_CTRL_PARTIAL_EN_WIDTH  1U
#define LCD_LCD_CTRL_PARTIAL_EN_MASK   0x00000020U

#define LCD_LCD_CTRL_BYTE_SWAP_SHIFT  6U
#define LCD_LCD_CTRL_BYTE_SWAP_WIDTH  1U
#define LCD_LCD_CTRL_BYTE_SWAP_MASK   0x00000040U

#define LCD_LCD_CTRL_FB_SEL_SHIFT  7U
#define LCD_LCD_CTRL_FB_SEL_WIDTH  1U
#define LCD_LCD_CTRL_FB_SEL_MASK   0x00000080U

#define LCD_LCD_CTRL_SOFT_RST_SHIFT  8U
#define LCD_LCD_CTRL_SOFT_RST_WIDTH  1U
#define LCD_LCD_CTRL_SOFT_RST_MASK   0x00000100U

#define LCD_LCD_CTRL_FORCE_CMD_SHIFT  9U
#define LCD_LCD_CTRL_FORCE_CMD_WIDTH  1U
#define LCD_LCD_CTRL_FORCE_CMD_MASK   0x00000200U

#define LCD_LCD_CTRL_DMA_SRC_SHIFT  10U
#define LCD_LCD_CTRL_DMA_SRC_WIDTH  1U
#define LCD_LCD_CTRL_DMA_SRC_MASK   0x00000400U

#define LCD_LCD_CTRL_AUTO_BUF_SEL_SHIFT  11U
#define LCD_LCD_CTRL_AUTO_BUF_SEL_WIDTH  1U
#define LCD_LCD_CTRL_AUTO_BUF_SEL_MASK   0x00000800U

#define LCD_LCD_STATUS_FRAME_DONE_SHIFT  0U
#define LCD_LCD_STATUS_FRAME_DONE_WIDTH  1U
#define LCD_LCD_STATUS_FRAME_DONE_MASK   0x00000001U

#define LCD_LCD_STATUS_CMD_DONE_SHIFT  1U
#define LCD_LCD_STATUS_CMD_DONE_WIDTH  1U
#define LCD_LCD_STATUS_CMD_DONE_MASK   0x00000002U

#define LCD_LCD_STATUS_FRAME_LATE_SHIFT  2U
#define LCD_LCD_STATUS_FRAME_LATE_WIDTH  1U
#define LCD_LCD_STATUS_FRAME_LATE_MASK   0x00000004U

#define LCD_LCD_STATUS_ADDR_OOB_SHIFT  3U
#define LCD_LCD_STATUS_ADDR_OOB_WIDTH  1U
#define LCD_LCD_STATUS_ADDR_OOB_MASK   0x00000008U

#define LCD_LCD_STATUS_STRIDE_ERR_SHIFT  4U
#define LCD_LCD_STATUS_STRIDE_ERR_WIDTH  1U
#define LCD_LCD_STATUS_STRIDE_ERR_MASK   0x00000010U

#define LCD_LCD_STATUS_AXI_ERR_SHIFT  5U
#define LCD_LCD_STATUS_AXI_ERR_WIDTH  1U
#define LCD_LCD_STATUS_AXI_ERR_MASK   0x00000020U

#define LCD_LCD_STATUS_FIFO_UNDERRUN_SHIFT  6U
#define LCD_LCD_STATUS_FIFO_UNDERRUN_WIDTH  1U
#define LCD_LCD_STATUS_FIFO_UNDERRUN_MASK   0x00000040U

#define LCD_LCD_STATUS_TE_TIMEOUT_SHIFT  7U
#define LCD_LCD_STATUS_TE_TIMEOUT_WIDTH  1U
#define LCD_LCD_STATUS_TE_TIMEOUT_MASK   0x00000080U

#define LCD_LCD_STATUS_MODE_SWITCH_ERR_SHIFT  8U
#define LCD_LCD_STATUS_MODE_SWITCH_ERR_WIDTH  1U
#define LCD_LCD_STATUS_MODE_SWITCH_ERR_MASK   0x00000100U

#define LCD_LCD_STATUS_SPI_BUSY_SHIFT  9U
#define LCD_LCD_STATUS_SPI_BUSY_WIDTH  1U
#define LCD_LCD_STATUS_SPI_BUSY_MASK   0x00000200U

#define LCD_LCD_STATUS_DMA_BUSY_SHIFT  10U
#define LCD_LCD_STATUS_DMA_BUSY_WIDTH  1U
#define LCD_LCD_STATUS_DMA_BUSY_MASK   0x00000400U

#define LCD_LCD_STATUS_FRAME_ACTIVE_SHIFT  11U
#define LCD_LCD_STATUS_FRAME_ACTIVE_WIDTH  1U
#define LCD_LCD_STATUS_FRAME_ACTIVE_MASK   0x00000800U

#define LCD_LCD_STATUS_CMD_BUSY_SHIFT  12U
#define LCD_LCD_STATUS_CMD_BUSY_WIDTH  1U
#define LCD_LCD_STATUS_CMD_BUSY_MASK   0x00001000U

#define LCD_LCD_STATUS_RESX_ACTIVE_SHIFT  13U
#define LCD_LCD_STATUS_RESX_ACTIVE_WIDTH  1U
#define LCD_LCD_STATUS_RESX_ACTIVE_MASK   0x00002000U

#define LCD_LCD_IRQ_EN_FRAME_DONE_EN_SHIFT  0U
#define LCD_LCD_IRQ_EN_FRAME_DONE_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_FRAME_DONE_EN_MASK   0x00000001U

#define LCD_LCD_IRQ_EN_CMD_DONE_EN_SHIFT  1U
#define LCD_LCD_IRQ_EN_CMD_DONE_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_CMD_DONE_EN_MASK   0x00000002U

#define LCD_LCD_IRQ_EN_FRAME_LATE_EN_SHIFT  2U
#define LCD_LCD_IRQ_EN_FRAME_LATE_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_FRAME_LATE_EN_MASK   0x00000004U

#define LCD_LCD_IRQ_EN_ADDR_OOB_EN_SHIFT  3U
#define LCD_LCD_IRQ_EN_ADDR_OOB_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_ADDR_OOB_EN_MASK   0x00000008U

#define LCD_LCD_IRQ_EN_STRIDE_ERR_EN_SHIFT  4U
#define LCD_LCD_IRQ_EN_STRIDE_ERR_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_STRIDE_ERR_EN_MASK   0x00000010U

#define LCD_LCD_IRQ_EN_AXI_ERR_EN_SHIFT  5U
#define LCD_LCD_IRQ_EN_AXI_ERR_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_AXI_ERR_EN_MASK   0x00000020U

#define LCD_LCD_IRQ_EN_FIFO_UNDERRUN_EN_SHIFT  6U
#define LCD_LCD_IRQ_EN_FIFO_UNDERRUN_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_FIFO_UNDERRUN_EN_MASK   0x00000040U

#define LCD_LCD_IRQ_EN_TE_TIMEOUT_EN_SHIFT  7U
#define LCD_LCD_IRQ_EN_TE_TIMEOUT_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_TE_TIMEOUT_EN_MASK   0x00000080U

#define LCD_LCD_IRQ_EN_MODE_SWITCH_ERR_EN_SHIFT  8U
#define LCD_LCD_IRQ_EN_MODE_SWITCH_ERR_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_MODE_SWITCH_ERR_EN_MASK   0x00000100U

#define LCD_LCD_IRQ_EN_CMD_HALF_EMPTY_EN_SHIFT  9U
#define LCD_LCD_IRQ_EN_CMD_HALF_EMPTY_EN_WIDTH  1U
#define LCD_LCD_IRQ_EN_CMD_HALF_EMPTY_EN_MASK   0x00000200U

#define LCD_LCD_FB0_ADDR_FB0_ADDR_SHIFT  0U
#define LCD_LCD_FB0_ADDR_FB0_ADDR_WIDTH  32U
#define LCD_LCD_FB0_ADDR_FB0_ADDR_MASK   0xFFFFFFFFU

#define LCD_LCD_FB1_ADDR_FB1_ADDR_SHIFT  0U
#define LCD_LCD_FB1_ADDR_FB1_ADDR_WIDTH  32U
#define LCD_LCD_FB1_ADDR_FB1_ADDR_MASK   0xFFFFFFFFU

#define LCD_LCD_STRIDE_STRIDE_SHIFT  0U
#define LCD_LCD_STRIDE_STRIDE_WIDTH  16U
#define LCD_LCD_STRIDE_STRIDE_MASK   0x0000FFFFU

#define LCD_LCD_PU_X_PU_X_START_SHIFT  0U
#define LCD_LCD_PU_X_PU_X_START_WIDTH  16U
#define LCD_LCD_PU_X_PU_X_START_MASK   0x0000FFFFU

#define LCD_LCD_PU_X_PU_X_END_SHIFT  16U
#define LCD_LCD_PU_X_PU_X_END_WIDTH  16U
#define LCD_LCD_PU_X_PU_X_END_MASK   0xFFFF0000U

#define LCD_LCD_PU_Y_PU_Y_START_SHIFT  0U
#define LCD_LCD_PU_Y_PU_Y_START_WIDTH  16U
#define LCD_LCD_PU_Y_PU_Y_START_MASK   0x0000FFFFU

#define LCD_LCD_PU_Y_PU_Y_END_SHIFT  16U
#define LCD_LCD_PU_Y_PU_Y_END_WIDTH  16U
#define LCD_LCD_PU_Y_PU_Y_END_MASK   0xFFFF0000U

#define LCD_LCD_SPI_CFG_SPI_DIV_SHIFT  0U
#define LCD_LCD_SPI_CFG_SPI_DIV_WIDTH  4U
#define LCD_LCD_SPI_CFG_SPI_DIV_MASK   0x0000000FU

#define LCD_LCD_SPI_CFG_SPI_MODE_SHIFT  4U
#define LCD_LCD_SPI_CFG_SPI_MODE_WIDTH  2U
#define LCD_LCD_SPI_CFG_SPI_MODE_MASK   0x00000030U

#define LCD_LCD_SPI_CFG_WIRE_3_SHIFT  6U
#define LCD_LCD_SPI_CFG_WIRE_3_WIDTH  1U
#define LCD_LCD_SPI_CFG_WIRE_3_MASK   0x00000040U

#define LCD_LCD_SPI_CFG_CS_SETUP_SHIFT  8U
#define LCD_LCD_SPI_CFG_CS_SETUP_WIDTH  4U
#define LCD_LCD_SPI_CFG_CS_SETUP_MASK   0x00000F00U

#define LCD_LCD_SPI_CFG_CS_HOLD_SHIFT  12U
#define LCD_LCD_SPI_CFG_CS_HOLD_WIDTH  4U
#define LCD_LCD_SPI_CFG_CS_HOLD_MASK   0x0000F000U

#define LCD_LCD_TE_CFG_TE_FPS_NUM_SHIFT  0U
#define LCD_LCD_TE_CFG_TE_FPS_NUM_WIDTH  8U
#define LCD_LCD_TE_CFG_TE_FPS_NUM_MASK   0x000000FFU

#define LCD_LCD_TE_CFG_TE_FPS_DEN_SHIFT  8U
#define LCD_LCD_TE_CFG_TE_FPS_DEN_WIDTH  8U
#define LCD_LCD_TE_CFG_TE_FPS_DEN_MASK   0x0000FF00U

#define LCD_LCD_TE_CFG_TE_TIMEOUT_SHIFT  16U
#define LCD_LCD_TE_CFG_TE_TIMEOUT_WIDTH  8U
#define LCD_LCD_TE_CFG_TE_TIMEOUT_MASK   0x00FF0000U

#define LCD_LCD_TE_CFG_TE_POL_SHIFT  24U
#define LCD_LCD_TE_CFG_TE_POL_WIDTH  1U
#define LCD_LCD_TE_CFG_TE_POL_MASK   0x01000000U

#define LCD_LCD_RESX_CFG0_RESX_WIDTH_SHIFT  0U
#define LCD_LCD_RESX_CFG0_RESX_WIDTH_WIDTH  16U
#define LCD_LCD_RESX_CFG0_RESX_WIDTH_MASK   0x0000FFFFU

#define LCD_LCD_RESX_CFG1_RESX_DELAY_SHIFT  0U
#define LCD_LCD_RESX_CFG1_RESX_DELAY_WIDTH  16U
#define LCD_LCD_RESX_CFG1_RESX_DELAY_MASK   0x0000FFFFU

#define LCD_LCD_RESX_CFG1_RESX_ASSERT_SHIFT  16U
#define LCD_LCD_RESX_CFG1_RESX_ASSERT_WIDTH  1U
#define LCD_LCD_RESX_CFG1_RESX_ASSERT_MASK   0x00010000U

#define LCD_LCD_CMD_FIFO_CMD_BYTE_SHIFT  0U
#define LCD_LCD_CMD_FIFO_CMD_BYTE_WIDTH  8U
#define LCD_LCD_CMD_FIFO_CMD_BYTE_MASK   0x000000FFU

#define LCD_LCD_CMD_FIFO_PAYLOAD_LEN_SHIFT  16U
#define LCD_LCD_CMD_FIFO_PAYLOAD_LEN_WIDTH  8U
#define LCD_LCD_CMD_FIFO_PAYLOAD_LEN_MASK   0x00FF0000U

#define LCD_LCD_CMD_STATUS_CMD_FIFO_LEVEL_SHIFT  0U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_LEVEL_WIDTH  6U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_LEVEL_MASK   0x0000003FU

#define LCD_LCD_CMD_STATUS_CMD_FIFO_FULL_SHIFT  6U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_FULL_WIDTH  1U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_FULL_MASK   0x00000040U

#define LCD_LCD_CMD_STATUS_CMD_FIFO_EMPTY_SHIFT  7U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_EMPTY_WIDTH  1U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_EMPTY_MASK   0x00000080U

#define LCD_LCD_CMD_STATUS_CMD_FIFO_HALF_EMPTY_SHIFT  8U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_HALF_EMPTY_WIDTH  1U
#define LCD_LCD_CMD_STATUS_CMD_FIFO_HALF_EMPTY_MASK   0x00000100U

#define LCD_LCD_ERR_ADDR_ERR_ADDR_SHIFT  0U
#define LCD_LCD_ERR_ADDR_ERR_ADDR_WIDTH  32U
#define LCD_LCD_ERR_ADDR_ERR_ADDR_MASK   0xFFFFFFFFU

#define LCD_LCD_VERSION_IP_VER_MINOR_SHIFT  0U
#define LCD_LCD_VERSION_IP_VER_MINOR_WIDTH  8U
#define LCD_LCD_VERSION_IP_VER_MINOR_MASK   0x000000FFU

#define LCD_LCD_VERSION_IP_VER_MAJOR_SHIFT  8U
#define LCD_LCD_VERSION_IP_VER_MAJOR_WIDTH  8U
#define LCD_LCD_VERSION_IP_VER_MAJOR_MASK   0x0000FF00U

#define LCD_LCD_VERSION_IP_ID_SHIFT  16U
#define LCD_LCD_VERSION_IP_ID_WIDTH  16U
#define LCD_LCD_VERSION_IP_ID_MASK   0xFFFF0000U

#define LCD_LCD_INFO_MAX_COL_SHIFT  0U
#define LCD_LCD_INFO_MAX_COL_WIDTH  12U
#define LCD_LCD_INFO_MAX_COL_MASK   0x00000FFFU

#define LCD_LCD_INFO_MAX_ROW_SHIFT  12U
#define LCD_LCD_INFO_MAX_ROW_WIDTH  12U
#define LCD_LCD_INFO_MAX_ROW_MASK   0x00FFF000U

#define LCD_LCD_FRAME_CTRL_FRAME_READY_SHIFT  0U
#define LCD_LCD_FRAME_CTRL_FRAME_READY_WIDTH  1U
#define LCD_LCD_FRAME_CTRL_FRAME_READY_MASK   0x00000001U

#define LCD_LCD_FRAME_CTRL_FRAME_COUNT_SHIFT  8U
#define LCD_LCD_FRAME_CTRL_FRAME_COUNT_WIDTH  8U
#define LCD_LCD_FRAME_CTRL_FRAME_COUNT_MASK   0x0000FF00U

#define LCD_LCD_LINEBUF_STATUS_BUF_A_FULL_SHIFT  0U
#define LCD_LCD_LINEBUF_STATUS_BUF_A_FULL_WIDTH  1U
#define LCD_LCD_LINEBUF_STATUS_BUF_A_FULL_MASK   0x00000001U

#define LCD_LCD_LINEBUF_STATUS_BUF_B_FULL_SHIFT  1U
#define LCD_LCD_LINEBUF_STATUS_BUF_B_FULL_WIDTH  1U
#define LCD_LCD_LINEBUF_STATUS_BUF_B_FULL_MASK   0x00000002U

#define LCD_LCD_LINEBUF_STATUS_BUF_A_EMPTY_SHIFT  2U
#define LCD_LCD_LINEBUF_STATUS_BUF_A_EMPTY_WIDTH  1U
#define LCD_LCD_LINEBUF_STATUS_BUF_A_EMPTY_MASK   0x00000004U

#define LCD_LCD_LINEBUF_STATUS_BUF_B_EMPTY_SHIFT  3U
#define LCD_LCD_LINEBUF_STATUS_BUF_B_EMPTY_WIDTH  1U
#define LCD_LCD_LINEBUF_STATUS_BUF_B_EMPTY_MASK   0x00000008U

#define LCD_LCD_LINEBUF_STATUS_ACTIVE_WR_BUF_SHIFT  4U
#define LCD_LCD_LINEBUF_STATUS_ACTIVE_WR_BUF_WIDTH  1U
#define LCD_LCD_LINEBUF_STATUS_ACTIVE_WR_BUF_MASK   0x00000010U

#define LCD_LCD_LINEBUF_STATUS_ACTIVE_RD_BUF_SHIFT  5U
#define LCD_LCD_LINEBUF_STATUS_ACTIVE_RD_BUF_WIDTH  1U
#define LCD_LCD_LINEBUF_STATUS_ACTIVE_RD_BUF_MASK   0x00000020U

#define LCD_LCD_SLAVE_BUFA_ADDR_BUFA_ADDR_SHIFT  0U
#define LCD_LCD_SLAVE_BUFA_ADDR_BUFA_ADDR_WIDTH  32U
#define LCD_LCD_SLAVE_BUFA_ADDR_BUFA_ADDR_MASK   0xFFFFFFFFU

#define LCD_LCD_SLAVE_BUFB_ADDR_BUFB_ADDR_SHIFT  0U
#define LCD_LCD_SLAVE_BUFB_ADDR_BUFB_ADDR_WIDTH  32U
#define LCD_LCD_SLAVE_BUFB_ADDR_BUFB_ADDR_MASK   0xFFFFFFFFU

#define LCD_LCD_SLAVE_INFO_APERTURE_SIZE_SHIFT  0U
#define LCD_LCD_SLAVE_INFO_APERTURE_SIZE_WIDTH  32U
#define LCD_LCD_SLAVE_INFO_APERTURE_SIZE_MASK   0xFFFFFFFFU

#endif /* __LCD_REGS_H__ */
